agent_name: "Caesar AI Assistant"
version: "1.0.0"
description: "AI-powered in-car assistant for rural Yalova simulation"

# LLM Configuration
llm:
  primary_model: "gpt-4-turbo-preview"
  fallback_model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 2048
  max_retries: 3
  timeout: 30

# Intent Classification
intent_classification:
  confidence_threshold: 0.6
  fallback_intent: "conversation"
  enable_context_learning: true

# Tool Execution
tool_execution:
  max_concurrent_tools: 3
  tool_timeout: 15
  retry_attempts: 2
  enable_mock_responses: true

# Dialogue Management
dialogue:
  default_language: "en"
  supported_languages: ["en", "tr"]
  tts_enabled: true
  response_delay: 0.5
  max_conversation_length: 50

# State Management
state:
  auto_save_interval: 60  # seconds
  max_history_size: 100
  context_window: 10
  enable_persistence: true

# Performance
performance:
  log_level: "INFO"
  enable_metrics: true
  max_memory_usage: "512MB"
  cache_size: 100

# Simulation Integration
simulation:
  environment: "yalova_rural"
  enable_events: true
  real_time_updates: true
  physics_enabled: false
